//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chemistry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chemistry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,H,Hydrogen
        ///2,He,Helium
        ///3,Li,Lithium
        ///4,Be,Beryllium
        ///5,B,Boron
        ///6,C,Carbon
        ///7,N,Nitrogen
        ///8,O,Oxygen
        ///9,F,Fluorine
        ///10,Ne,Neon
        ///11,Na,Sodium
        ///12,Mg,Magnesium
        ///13,Al,Aluminum
        ///14,Si,Silicon
        ///15,P,Phosphorus
        ///16,S,Sulfur
        ///17,Cl,Chlorine
        ///18,Ar,Argon
        ///19,K,Potassium
        ///20,Ca,Calcium
        ///21,Sc,Scandium
        ///22,Ti,Titanium
        ///23,V,Vanadium
        ///24,Cr,Chromium
        ///25,Mn,Manganese
        ///26,Fe,Iron
        ///27,Co,Cobalt
        ///28,Ni,Nickel
        ///29,Cu,Copper
        ///30,Zn,Zinc
        ///31,Ga,Gallium
        ///32,Ge,Germanium
        ///33,As,Arsenic
        ///34,Se,Selenium
        ///35,Br,Bromine
        ///36,K [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string elementlist {
            get {
                return ResourceManager.GetString("elementlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] jquery_pte {
            get {
                object obj = ResourceManager.GetObject("jquery_pte", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
